name: publish
on:
  push:
    branches: [ main ]
jobs:
  publish:
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, 'semantic-release') && !contains(github.event.head_commit.message, 'skip-ci')
    runs-on: ubuntu-latest
    name: Publish Release
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.0
      - name: Install Semantic Release
        run: |
          python3 -m pip install python-semantic-release
      - name: Make Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "Wolf Gear"
          git config --global user.email "opensource@wolfgear.tech"
          echo 'https://github.com/${{ github.event.repository.full_name }}.git'
          git remote set-url origin https://github.com/${{ github.event.repository.full_name }}.git
          semantic-release publish -D commit_author="Wolf Gear <opensource@wolfgear.tech>"
